spring.application.name=Mobile_Money_Integration_System

server.port=8080

spring.datasource.url=jdbc:h2:mem:mobilemoneydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-256-bit-secret-key-change-this-in-production-please
jwt.expiration-ms=86400000
